version: '3.7'

services:
    autok3s:
        container_name: "${COMPOSE_PROJECT_NAME}"
        image: "cnrancher/autok3s:v0.4.3"
        restart: unless-stopped
        stdin_open: true
        tty: true
        ports:
            - '127.0.0.1:8080:8080'
            #- '8080:8080'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
